INSERT INTO Movies (title, release_year, genre, description) VALUES
('The Shawshank Redemption', 1994, 'Drama', 'A man wrongly convicted of murder forms a remarkable friendship with a fellow inmate and finds redemption.'),
('The Godfather', 1972, 'Crime, Drama', 'An epic tale of a mafia family, power struggles, and loyalty.'),
('The Dark Knight', 2008, 'Action, Crime', 'Batman battles the Joker in a war for Gotham''s soul.'),
('Forrest Gump', 1994, 'Drama, Romance', 'A man with a kind heart journeys through decades of U.S. history, influencing key events.'),
('Inception', 2010, 'Action, Sci-Fi', 'A thief enters dreams to steal secrets in this mind-bending sci-fi thriller.'),
('The Matrix', 1999, 'Action, Sci-Fi', 'A hacker discovers reality is a simulated illusion and joins the fight against its controllers.'),
('Fight Club', 1999, 'Drama', 'An insomniac office worker forms an underground fight club that evolves into something much more.'),
('Pulp Fiction', 1994, 'Crime, Drama', 'Interwoven stories reveal a series of crime and intrigue.'),
('Schindler''s List', 1993, 'Drama, History', 'A businessman saves the lives of Jewish refugees during the Holocaust.'),
('The Lion King', 1994, 'Animation, Drama', 'A young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.'),
('Spirited Away', 2001, 'Animation, Fantasy', 'A young girl navigates a mysterious world to save her parents.'),
('Life is Beautiful', 1997, 'Comedy, Drama', 'A Jewish Italian bookshop owner uses his imagination to protect his son in a Nazi concentration camp.'),
('The Grand Budapest Hotel', 2014, 'Comedy, Drama', 'The adventures of a legendary concierge at a famous hotel.'),
('Gladiator', 2000, 'Action, Drama', 'A betrayed Roman general seeks revenge against the corrupt emperor who murdered his family.'),
('Avatar', 2009, 'Action, Sci-Fi', 'A paraplegic Marine is dispatched to the moon Pandora on a unique mission.'),
('Titanic', 1997, 'Drama, Romance', 'A young man and woman from different social classes fall in love aboard the ill-fated RMS Titanic.'),
('La La Land', 2016, 'Drama, Music', 'A musician and an aspiring actress meet and fall in love in Los Angeles.'),
('The Silence of the Lambs', 1991, 'Crime, Drama', 'A young FBI cadet seeks the help of an incarcerated cannibalistic serial killer to catch another serial killer.'),
('Interstellar', 2014, 'Adventure, Sci-Fi', 'A team of explorers travel through a wormhole in space in an attempt to save humanity.'),
('The Prestige', 2006, 'Drama, Mystery', 'Two magicians engage in a battle to create the ultimate illusion while sacrificing everything they have.'),
('Jurassic Park', 1993, 'Action, Adventure', 'A theme park''s cloned dinosaurs run amok, presenting unforeseen dangers.'),
('The Green Mile', 1999, 'Crime, Drama', 'The lives of guards on Death Row are affected by one of their charges: a black man accused of heinous crimes.');